### ISSUE TITLE
pif-scan causes a crash when infiniband interface is present.

### ISSUE THREAD

**Issue by Oleszkiewicz** [xapi-project/xcp-networkd#184] opened 2021-02-11 18:07 UTC
On old (pre 8.0) versions it actually worked, now it crashes with internal error when infiniband interface is present in the system, probably caused by a different size of MAC address. The interface actually works, just crashes pif-scan

**Comment by edwintorok** [comment] 2021-02-11 18:14
Can you open a ticket on bugs.xenserver.org and attach the output from xen-bugtool? (attaching logs on github is probably not recommended, because then everyone can see it)
How does pif-scan crash, does it exit with error, or do you see a crash in dmesg?

**Comment by Oleszkiewicz** [comment] 2021-02-11 18:19
I will, it crashes with internal error, as a result even eth interfaces are not scanned properly when ib is present.
Also I can post some logs from a test machine that do not include any private data:

These logs are taken from the same machine :

IB driver unloaded -scan works: 
https://gist.github.com/Oleszkiewicz/93db24d5ecf48e45c0620fcffac39dc0

IB Driver loaded - scan fails:
https://gist.github.com/Oleszkiewicz/f3408bead32282e3f6214c0c434545d6

This happens on xcp-ng 8.0-8.2 on some older version it actually detected IB interfaces properly.

**Comment by edwintorok** [comment] 2021-02-11 18:28
Thanks, unfortunately the stacktrace from xcp_networkd is missing (says backtrace table not initialized). There is a backtrace from xapi, but that just stops at the IDL level. We probably need to take a look at the full logs to understand what went wrong here.

**Comment by Oleszkiewicz** [comment] 2021-02-11 18:38
hmm i dont get anything more in logs, how can I generate backtrace from xcp_networkd ? any pointers? I will be happy to assist in debugging this

**Comment by Oleszkiewicz** [comment] 2021-02-11 20:01
btw. bugs.xenserver.org is down :(

**Comment by edwintorok** [comment] 2021-02-11 20:16
Did you use https? https://bugs.xenserver.org/ The http redirect might be down.

**Comment by robhoes** [comment] 2021-02-12 10:08
When you say "crash", it seems that you mean that the pif-scan called failed, but not that any daemons exited? The logs on your link suggest that some `List.hd` call in xcp-networkd failed due to a list that was unexpectedly empty. We should eliminate all `List.hd` calls and properly handle the empty-list case.

**Comment by robhoes** [comment] 2021-02-12 10:12
For example, I don't like the looks of the error handling around this one (in spite of what the code comment suggests): https://github.com/xapi-project/xcp-networkd/blob/master/lib/network_utils.ml#L164.

**Comment by Oleszkiewicz** [comment] 2021-02-12 10:22
yes, pif-scan failed, daemons live AFAIK. 
I guess that empty-list case could be one of the problems, however another thing is properly handling the IB different MAC format actually the strange thing is that it was supported properly already and then was broken... 
Actually it should be pretty straightforward as there is no reason/need to assign IB interfaces to guests / bridging etc, so no "infiniband magic" here. What is important is:
1) be able to see ETH interfaces while IB is present in the system (and handling errors properly should solve this), also this is a heavyweight bug as it causes emergency network reset to come back with no network interfaces if IB is present in the system. 
2) be able to see IB interface just to allow it to be added to guest as SR-IOV VF interface. on the OS side - this works, on the xen side - is should also work already (there is nothing different in assigning ib VP port vs eth VF port)...  I guess it could be trivial to the person who knows this code well, as mentioned - it was already working well, so I guess some change caused IB present to cause an empty list and -> internal error.

**Comment by robhoes** [comment] 2021-02-12 10:29
We've added SR-IOV support some time ago (perhaps 8.0), which caused some changes in how interfaces are discovered. We didn't test this with Infiniband as far as I know, so that may have broken it. I bet it's just a matter of catching some corner cases (especially if it used to work before).

**Comment by Oleszkiewicz** [comment] 2021-02-12 10:33
I guess so. I think that if the interface discovery is corrected the SR-IOV should work with IB right out of the box (especially that we actually just pass the PCIe VF device to the guest and the rest is the job of the driver inside the guest.?

**Comment by lindig** [comment] 2021-02-12 11:02
```
utop # String.split_on_char '\n' "";;
- : string list = [""]
```

**Comment by robhoes** [comment] 2021-02-12 11:13
Perhaps not that one then :)
Some other candidates are: https://github.com/xapi-project/xcp-networkd/blob/master/lib/network_utils.ml#L485-L487

**Comment by lindig** [comment] 2021-02-12 11:16
I agree with the sentiment - we should always use `match` for these cases and log an error including a code position when the thought-to-be impossible happens.

**Comment by lindig** [comment] 2021-02-12 13:39
This is a candidate:

* https://github.com/xapi-project/xcp-networkd/blob/master/lib/network_utils.ml#L207

```

**Comment by lindig** [comment] 2021-02-12 14:00
*  `let get_mtu dev = int_of_string (List.hd (link dev "mtu"))`
*  `let get_mac dev = List.hd (link dev "link/ether")`
* `link` is calling `find`, which can return an empty list:

```
utop # find "" "";;
- : string list = []
utop # find "x" "";;
- : string list = []
utop # find "/" "foo";;
- : string list = []
```

**Comment by lindig** [comment] 2021-02-12 14:08
The command is parsing the output of `/sbin/ip link show dev /some/device`. Are there any surprises in that output for the IB device?

**Comment by Oleszkiewicz** [comment] 2021-02-12 14:31
let me check

**Comment by Oleszkiewicz** [comment] 2021-02-12 14:39
[15:38 Fenrir ~]# ip link show dev ib0
18: ib0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP mode DEFAULT group default qlen 256
    link/infiniband a0:00:02:20:fe:80:00:00:00:00:00:00:24:be:05:ff:ff:cb:db:b1 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff

**Comment by lindig** [comment] 2021-02-12 14:41
My suspicion: `"link/ether"` is not found because it is `"link/infiniband"`

**Comment by Oleszkiewicz** [comment] 2021-02-12 14:48
1) this should not kill the whole scan process, at best it should cause the device to be undetected.
2) if this is the culprit it should be pretty simple to repair this I guess and allow xcp-networkd to see ib interfaces again ?

**Comment by lindig** [comment] 2021-02-12 14:50
I agree. The problem is the uncaught exception which kills the scan process. The code relies on always finding `link/ether`, which is wrong.

**Comment by lindig** [comment] 2021-02-12 16:01
A potential fix - not yet too happy about it: https://github.com/xapi-project/xcp-networkd/pull/185

**Comment by Oleszkiewicz** [comment] 2021-02-12 16:03
how could I test this on the server in the fastest way :)?

**Comment by lindig** [comment] 2021-02-12 16:05
I am building this on top of our code base but it would be backported to CH 8.2 at least. I can build a binary for CH 8.2 for you and share it - but that would be on Monday.

**Comment by Oleszkiewicz** [comment] 2021-02-12 16:11
This would be awesome :) Thank you and waiting for Monday then.

**Comment by Oleszkiewicz** [comment] 2021-02-15 13:49
any possibility to try it out on 8.2 and see if any problems arise?

**Comment by lindig** [comment] 2021-03-02 09:16
Closing this. Infiniband hardware is unsupported and I understand that this is not fully resolved but we simply don't have the capacity to work on this and also lack the hardware to test it.

**Closed by lindig** 2021-03-02 09:16 UTC
